workflows:
  ios-personal-workflow:
    name: iOS Personal Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.jejo.flashcardsapp  # Pon aquí tu identificador (ejemplo: com.jeluva.flashcards)
      vars:
        # Si tienes un workspace y scheme, agrégalos aquí; si no, puedes probar omitir estas líneas o usar los valores predeterminados que Buildozer genere.
        XCODE_WORKSPACE: "flashcardsapp.xcworkspace"  # Reemplaza si lo conoces, o déjalo vacío
        XCODE_SCHEME:   "flashcardsappScheme"              # Reemplaza si lo conoces, o déjalo vacío
    scripts:
      - name: Build IPA for personal use
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
